---
# Playbook to run a private Docker Hub image for a webapp
# cd ansible
# ansible-playbook -i inventory/hosts.yaml playbooks/install_docker_webapp.yaml
- name: Install Docker
  hosts: webserver1

  tasks:

  # Create directory for docker configs.
  file:
    path: ~/.docker
    state: directory
    mode: 0700

# Copies the config.json file containing Docker Hub credentials
- name: Copy Docker config 
  copy:
    src: ~/.docker2/config.json   
    dest: ~/.docker/config.json
    mode: 0600

  # Pulls private image from Docker Hub using credentials  
  - name: Pull private Docker Hub image
    docker_image:
      name: henry808/webapp_private
      tag: latest
      source: pull

  # Runs a container using the private Docker Hub image
  - name: Run container from image
    docker_container:
      name: webapp
      image: henry808/webapp_private:latest
      ports:
        - "8080:8080"
      state: started