---
# Playbook to run a private Docker Hub image for a webapp
- name: Install Docker
  hosts: webserver1

  tasks:

  # Copies the config.json file containing Docker Hub credentials
  - name: Copy Docker credentials config

    copy:
      src: ~/.docker/config.json
      dest: ~/.docker/config.json
      mode: 0600

  # Pulls private image from Docker Hub using credentials  
  - name: Pull private Docker Hub image
    docker_image:
      name: henry808/webapp_private
      tag: latest
      source: pull

  # Runs a container using the private Docker Hub image
  - name: Run container from image
    docker_container:
      name: webapp
      image: henry808/webapp_private:latest
      ports:
        - "8080:8080"
      state: started