---
# Playbook to run a private Docker Hub image for a webapp
# cd ansible
# ansible-playbook -i inventory/hosts.yaml playbooks/install_docker_webapp.yaml
- name: Install Docker
  hosts: webserver1

  tasks:
  # To use docker command
  - name: Install docker python module to run docker tasks
    pip:
      name: docker-py
      state: present

  # Pulls private image from Docker Hub using credentials  
  - name: Pull private Docker Hub image
    docker_image:
      name: henry808/webapp_private
      tag: latest
      source: pull

  # Runs a container using the private Docker Hub image
  - name: Run container from image
    docker_container:
      name: webapp
      image: henry808/webapp_private:latest
      ports:
        - "8080:8080"
      state: started